### ISSUE TITLE
Should we support specific version installs of Steampipe via brew?

### ISSUE THREAD

**Issue by e-gineer** [turbot/homebrew-tap#38]
For example, after the release of `v0.17.0`, should you still be able to do something like this?
```
brew install steampipe@0.16.4
```

**Comment by pskrbasu** [comment]
94fc00c6b4ace5859dc321bde5ca1a384b14ec7c

**Comment by pskrbasu** [comment]
Completed https://github.com/turbot/steampipe/pull/2759. Now users will be able to install specific versions of steampipe using brew.
