### ISSUE TITLE
Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by jhult** [turbot/homebrew-tap#4]
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the turbot/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/turbot/homebrew-tap/Formula/steampipe.rb:8
```

**Comment by pskrbasu** [comment]
Hey @jhult, Sorry, it's been ages. 

I can't seem to reproduce this `Warning` anymore. We have changed our formula a lot over time, which might have unknowingly resolved the `Warning: Calling bottle :unneeded is deprecated! There is no replacement` warning you were seeing.

If you are still seeing this, please let us know here.

Thanks
